Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -37,8 +37,8 @@ jobs:
       #     ls
       #     cat "buildSummary${GITHUB_RUN_ID}.json"
       - run: |
-        echo "::error file=tAnswerIsCorrect.m,line=10,endLine=12,title=Run MATLAB Tests exited with non-zero exit code::Verification failed in tAnswerIsCorrect/verifyCorrect"
-        exit 1
+          echo "::error file=tAnswerIsCorrect.m,line=10,endLine=12,title=Run MATLAB Tests exited with non-zero exit code::Verification failed in tAnswerIsCorrect/verifyCorrect"
+          exit 1
 
       # As an alternative to run-tests, you can use run-command to execute a MATLAB script, function, or statement.
       #- name: Run all tests
